# Application Configuration
  spring.application.name=library-management-backend

#current profile is dev [dev/prod]
spring.profiles.active=dev

  # Main Application Settings
spring.main.banner-mode=off
spring.main.log-startup-info=false

# Logging Configuration
# logging.level.root=WARN
# logging.level.mayur.dev.book_management_system=INFO
# logging.level.org.springframework.web=WARN